### PR TITLE
Version Bump -> 0.19.1

### PR DESCRIPTION
**Pull request by logston**

### CODE REVIEW

**Comment by logston** [comment]
One more @bartoszgrabski! Thank you!

**Comment by logston** [comment]
Once this is merged, we need to run: 

```
poetry build
poetry publish
```

**Comment by logston** [comment]
Test is failing due to https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954

Will retry codecov test tomorrow.

**Review by bartoszgrabski — APPROVED** [review]

**Comment by ematthewsBW** [comment]
there is no git tag nor github release for 0.19.1. At the moment it skips from 0.19.0 to 0.20.0. Meanwhile 0.20.0 is not published to pypi

**Pull request merged**
