### PR TITLE
Compatibility for calling unbound function on Python 2

### PR DESCRIPTION
**Pull request by pablodiazgutierrez**
If the modern mode fails with a TypeError, fallback to using __func__().

### CODE REVIEW

**Comment by logston** [comment]
Hey @pablodiazgutierrez, happy to merge this after a rebase but FYI, I'm going to be making some major updates to this file soon.

**Comment by pablodiazgutierrez** [comment]
I appreciate that. I did notice some conflicts when I last tried to update. How can I help>

-Pablo

**Comment by logston** [comment]
@pablodiazgutierrez Thanks for your patience. Can you rebase your changes? Happy to merge in after that. Please note though, we are not looking to major moves towards Python 2 compatibility. These changes will be some of the last and may be removed within the year as part of future releases. 

Again, thank you very much for your work!

**Comment by logston** [comment]
Actually, now that I am reviewing the code, there are a lot of f-string uses. I'm sorry, but Python 2 will not work with this code base anymore.

**Comment by pablodiazgutierrez** [comment]
Yeah no big deal, I’m maintaining my own fork and it’s ok for us. Soon we’ll migrate to Python 3 anyway. Thanks for checking!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by logston** [comment]
Sorry @pablodiazgutierrez. Since we've moved fully to Python3, I will not be merging this. Many thanks for your work though!

**Comment by pablodiazgutierrez** [comment]
I understand, no problem!

**Pull request closed without merging**
