### PR TITLE
Increase testing

### PR DESCRIPTION
**Pull request by logston**
This commit increases the testing of this library. Now it is
  explicitly tested over all supported versions of Django.

### CODE REVIEW

**Comment by logston** [comment]
@koliber, friendly ping.

**Comment by koliber** [comment]
Hi @logston . To be clear, do you need me to review this PR, merge it, or something else?

**Comment by logston** [comment]
Hey @koliber! Just a review with an acceptance would be great. Not sure who's responsible for SCIM these days so I reached out to you.

**Review by koliber — APPROVED** [review]
👍

**Pull request merged**
